---
- name: set up a local machine to my liking
  hosts: 127.0.0.1
  connection: local
  become: True
  tasks:

  - package: name={{ item }} state=installed
    with_items:
      - rbenv
      - vim
      - ruby-build
      - aptitude
      - ruby2.3-dev

  - apt_key:
      keyserver: keyserver.ubuntu.com
      id: A3D8A366869FE2DC5FFD79C36A9653F936FD5529

  - apt_repository:
      repo: 'deb http://ppa.launchpad.net/atareao/telegram/ubuntu xenial main'

  - package: name=telegram
