---
- name: set up a local machine to my liking
  hosts: 127.0.0.1
  connection: local
  become: True
  tasks:

  - package: name={{ item }} state=installed
    with_items:
      - rbenv
      - vim
      - ruby-build
      - aptitude

  - name: Xenial specific packages
    package: name={{ item }}
    with_items:
      - ruby2.3-dev
      - redshift
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] == "16"

  - name: Bionic specific packages
    package: name={{ item }}
    with_items:
      - ruby2.5-dev
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] == "18"


  - apt_key:
      keyserver: keyserver.ubuntu.com
      id: A3D8A366869FE2DC5FFD79C36A9653F936FD5529

  - apt_repository:
      repo: 'deb http://ppa.launchpad.net/atareao/telegram/ubuntu xenial main'

  - package: name=telegram

  - lineinfile:
      dest: /home/mattp/.bash_profile
      owner: mattp
      group: mattp
      mode: 0640
      line: 'export EDITOR=vim'
      create: yes
