---
- name: set up a local machine to my liking
  hosts: 127.0.0.1
  connection: local
  tasks:

    - package: name={{ item }} state=installed
      with_items:
        - vim
        - aptitude
        - wget
        - curl
        - strace
        - jq
        - firefox

    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: A3D8A366869FE2DC5FFD79C36A9653F936FD5529

    - lineinfile:
        dest: /home/mattp/.bash_profile
        mode: 0640
        line: 'export EDITOR=vim'
        create: yes

    - name: download lastpass firefox plugin
      get_url:
        url: https://addons.mozilla.org/firefox/downloads/file/4246455/lastpass_password_manager-4.127.0.1.xpi
        dest: /tmp
      register: lastpass_plugin

    - name: install lastpass firefox plugin
      shell: firefox /tmp/lastpass_password_manager-4.127.0.1.xpi
      when: lastpass_plugin.changed

    - name: download adblock firefox plugin
      get_url:
        url: https://addons.mozilla.org/firefox/downloads/file/4312959/adblock_plus-4.3.xpi
        dest: /tmp
      register: adblock_plugin

    - name: install adblock firefox plugin
      shell: firefox /tmp/adblock_plus-4.3.xpi
      when: adblock_plugin.changed
