---
- name: Set up a local machine to my liking
  hosts: 127.0.0.1
  connection: local
  collections:
    - ansible.posix
  tasks:
    - name: Update package cache
      apt:
        update_cache: true
      become: true

    - name: Install some useful packages
      ansible.builtin.package:
        name: "{{ item }}"
      become: true
      with_items:
        - vim
        - aptitude
        - wget
        - curl
        - strace
        - jq
        - firefox

    - name: Add common packae signing keys
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: A3D8A366869FE2DC5FFD79C36A9653F936FD5529
      become: true

    - name: Configure an editor
      ansible.builtin.lineinfile:
        dest: /home/mattp/.profile
        mode: "0640"
        line: 'export EDITOR=vim'
        create: true

    - name: Add some SSH keys
      ansible.posix.authorized_key:
        user: mattp
        key: https://github.com/mattpep.keys
        validate_certs: false

    - name: Download lastpass firefox plugin
      ansible.builtin.get_url:
        url: https://addons.mozilla.org/firefox/downloads/file/4246455/lastpass_password_manager-4.127.0.1.xpi
        dest: /home/mattp
        mode: "0644"
        owner: mattp
        group: mattp
      register: lastpass_plugin

    - name: Install lastpass firefox plugin
      ansible.builtin.command: firefox /home/mattp/lastpass_password_manager-4.127.0.1.xpi
      when: lastpass_plugin.changed

    - name: Download adblock firefox plugin
      ansible.builtin.get_url:
        url: https://addons.mozilla.org/firefox/downloads/file/4312959/adblock_plus-4.3.xpi
        dest: /home/mattp
        mode: "0644"
        owner: mattp
        group: mattp
      register: adblock_plugin

    - name: Install adblock firefox plugin
      ansible.builtin.command: firefox /home/mattp/adblock_plus-4.3.xpi
      when: adblock_plugin.changed
